### ISSUE TITLE
Buttons don't align on ESP list

### ISSUE THREAD

**Issue by Arzhem** [DimitarSamarov07/esp-cloud-remote#4]
The buttons on the ESP list don't align propertly when multiple are displayed.
![image](https://github.com/user-attachments/assets/e4a1f9c3-0caf-44ce-beec-e6aacb04c4a5)
They should align like in the esp-light-demo branch.
![image](https://github.com/user-attachments/assets/881ad00e-74cb-41ad-a498-854c325ccf11)

**Comment by DimitarSamarov07** [comment]
Follow up with ECR-27

**Comment by DimitarSamarov07** [comment]
PR #5 fixes the issue. Thank you
